Repository Do-Farming/do-farming_Front, pull requests merged in 2024-07, with the labels that each got.

#48 feat: Axios Instance
  package-lock.json
  package.json
  src/apis/authService.ts
  src/apis/axiosInstance.ts
  src/screens/sign/SignInScreen.tsx
  src/states/authState.ts
  src/types/auth/AuthTypes.ts
  src/types/common/CommonTypes.ts
  src/types/common/index.ts
  src/utils/tokenService.ts
Labels: Feat 🐯

#55 feat: 기상 미션 렌딩페이지
  App.tsx
  src/screens/ExampleScreen.tsx
  src/screens/pedometer/PedometerScreen.styled.ts
  src/screens/wakeup/WakeupScreen.styled.ts
  src/screens/wakeup/WakeupScreen.tsx
Labels: Feat 🐯

#59 feat: 카메라 찍기, 다시찍기, 프리뷰 보기 기능
  App.tsx
  src/screens/wakeup/camera/CameraScreen.styled.ts
  src/screens/wakeup/camera/CameraScreen.tsx
  src/screens/wakeup/wakeup/WakeupScreen.styled.ts
  src/screens/wakeup/wakeup/WakeupScreen.tsx
Labels: Feat 🐯

#62 feat: 챗봇 화면 개발, 이미지 생성 샘플화면 개발
  App.tsx
  package-lock.json
  package.json
  src/assets/svg/ic_arrowUp.svg
  src/assets/svg/index.ts
  src/screens/ExampleScreen.tsx
  src/screens/ExploreScreen.tsx
  src/screens/chatbot/ChatBotScreen.styled.ts
  src/screens/chatbot/ChatBotScreen.tsx
  src/screens/imageCreation/ImageCreationScreen.tsx
  src/screens/sign/SignInScreen.tsx
Labels: Feat 🐯, Style 🌈

#69 refactor: 메인페이지 성능 최적화
  src/screens/home/HomeScreen.tsx
Labels: Refactor ⚒️

#68 refactor: dall-e-3를 사용하며 request body에 직접 전송하는 방식으로 변경
  src/screens/imageCreation/ImageCreationScreen.tsx
  src/screens/wakeup/wakeup/WakeupScreen.tsx
Labels: Refactor ⚒️

#72 feat: 메인페이지 카드 비율 동적 렌더링
  src/components/CardImage/CardImage.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/home/HomeScreen.tsx
Labels: Feat 🐯

#74 style: 메인페이지 SafeArea 적용 및 카드 리스트 디자인 수정
  App.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/home/HomeScreen.tsx
Labels: Style 🌈

#75 feat: 객체 탐지 일치성 확인 후 처리
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  src/apis/wakeupService.ts
  src/screens/wakeup/camera/CameraScreen.styled.ts
  src/screens/wakeup/camera/CameraScreen.tsx
Labels: Feat 🐯

#76 style: 메인페이지 디자인 수정
  src/screens/home/HomeScreen.styled.ts
  src/screens/home/HomeScreen.tsx
Labels: Style 🌈

#79 refactor: App.tsx 코드 분리
  App.tsx
  src/navigators/StackNavigator.tsx
  src/navigators/TabNavigator.tsx
Labels: Refactor ⚒️

#81 style: 이상형 월드컵 css 수정 및 동적 디자인 버튼
  package.json
  src/components/CardImage/CardImage.tsx
  src/navigators/StackNavigator.tsx
  src/screens/generateCard/GenerateCardScreen.tsx
  src/screens/worldcup/card/CardWorldCupScreen.styled.ts
  src/screens/worldcup/card/CardWorldCupScreen.tsx
  src/screens/worldcup/card/CardWorldCupWinnerScreen.styled.ts
  src/screens/worldcup/card/CardWorldCupWinnerScreen.tsx
Labels: enhancement, Style 🌈

#90 feat: 챌린지 방 생성 서버통신
  package-lock.json
  src/apis/bangService.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/types/BangTypes.ts
Labels: Feat 🐯

#103 feat: 이상형 월드컵
  src/apis/axiosInstance.ts
  src/navigators/StackNavigator.tsx
  src/screens/ExampleScreen.tsx
  src/screens/generateCard/GenerateCardScreen.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/worldcup/card/CardWorldCupScreen.styled.ts
  src/screens/worldcup/information/WorldCupInfoScreen.styled.ts
  src/screens/worldcup/information/WorldCupInfoScreen.tsx
  src/screens/worldcup/select/WorldCupSelectScreen.styled.ts
  src/screens/worldcup/select/WorldCupSelectScreen.tsx
  src/screens/worldcup/taste/TasteWorldCupScreen.styled.ts
  src/screens/worldcup/taste/TasteWorldCupScreen.tsx
  src/screens/worldcup/winner/CardWorldCupWinnerScreen.styled.ts
  src/screens/worldcup/winner/CardWorldCupWinnerScreen.tsx
  src/types/taste/TasteTypes.ts
Labels: Feat 🐯

#102 feat: 만보계 API 연결
  src/apis/axiosInstance.ts
  src/screens/pedometer/PedometerScreen.tsx
  src/types/competition/WalkChallengeTypes.ts
  src/types/competition/index.ts
Labels: Feat 🐯

#108 feat: 내 입출금 계좌 조회 api 통신
  src/apis/accountService.ts
  src/apis/axiosInstance.ts
  src/screens/bang/bangJoin/BangJoinScreen.tsx
  src/types/account/AccountTypes.ts
Labels: Feat 🐯

#110 feat: 플로우 연결
  src/navigators/StackNavigator.tsx
  src/navigators/TabNavigator.tsx
  src/screens/ExampleScreen.tsx
  src/screens/hana/HanaMainScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
  src/screens/home/HomeScreen.tsx
  src/screens/mypage/MyPageScreen.styled.ts
  src/screens/sign/SignInScreen.tsx
  src/screens/sign/SignUpScreen.tsx
Labels: Refactor ⚒️

#111 feat: 두파밍 상품 가입 플로우 수정 및 화면 추가
  src/navigators/StackNavigator.tsx
  src/screens/bang/bangCreate/BangCreateScreen.styled.ts
  src/screens/bang/bangJoin/BangJoinScreen.styled.ts
  src/screens/bang/bangJoin/BangJoinScreen.tsx
  src/screens/bang/bangJoin/BangJoinScreen2.tsx
  src/screens/product/ProductSignUpScreen.styled.ts
  src/screens/product/ProductSignUpScreen.tsx
  src/screens/product/complete/ProductSignInScreen.tsx
Labels: Feat 🐯

#113 fix: 챌린지 방 생성시 출금계좌 및 가입 프로세스 추가
  src/screens/bang/bangCreate/BangCreateScreen.styled.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
Labels: Feat 🐯

#84 feat:SendMoneyScreen api 연결
  src/screens/bankingService/SendMoneyScreen.tsx
Labels: Feat 🐯

#86 [feat] App.tsx에 push알람 받기 및 보내기 추가
  App.tsx
Labels: Feat 🐯

#115 feat: 챌린지 방 생성 시 두파밍 상품 비밀번호 설정, 두파밍 상품 가입 서버통신
  src/apis/accountService.ts
  src/apis/axiosInstance.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/screens/bang/bangJoin/BangJoinScreen2.tsx
  src/screens/product/auth/ProductPasswordScreen.tsx
  src/types/account/AccountTypes.ts
Labels: bug, Feat 🐯

#118 fix: 방 생성하기 api 로직 수정
  src/apis/accountService.ts
  src/apis/bangService.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/screens/product/auth/ProductPasswordScreen.tsx
Labels: bug, enhancement

#116 feat: 나만의 카드 생성
  src/assets/svg/dofarming.svg
  src/assets/svg/ic_chip.svg
  src/assets/svg/ic_doFarming.svg
  src/assets/svg/index.ts
  src/navigators/StackNavigator.tsx
  src/screens/generateCard/GenerateCardScreen.styled.ts
  src/screens/generateCard/GenerateCardScreen.tsx
  src/screens/imageCreation/ImageCreationScreen.tsx
  src/screens/worldcup/information/WorldCupInfoScreen.tsx
  src/screens/worldcup/winner/CardWorldCupWinnerScreen.styled.ts
  src/screens/worldcup/winner/CardWorldCupWinnerScreen.tsx
Labels: Feat 🐯

#121 feat: 거래내역 조회
  App.tsx
  package-lock.json
  package.json
  src/navigators/StackNavigator.tsx
  src/screens/ExampleScreen.tsx
  src/screens/transactionHistory/TransactionHistoryScreen.styled.ts
  src/screens/transactionHistory/TransactionHistoryScreen.tsx
  src/styles/theme.ts
Labels: Feat 🐯

#122 feat: 참여자 - 두파밍 상품 api 통신 연결
  src/apis/bangService.ts
  src/assets/svg/cancel.svg
  src/assets/svg/index.ts
  src/navigators/TabNavigator.tsx
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/screens/bang/bangDetail/BangDetailScreen.tsx
  src/screens/bang/bangJoin/BangJoinScreen.tsx
  src/screens/bang/bangJoin/BangJoinScreen2.tsx
  src/screens/product/auth/ProductPasswordScreen.tsx
  src/screens/product/complete/ProductSignInScreen.styled.ts
  src/screens/product/complete/ProductSignInScreen.tsx
  src/screens/sign/SignInScreen.tsx
  src/screens/worldcup/winner/CardWorldCupWinnerScreen.tsx
Labels: Feat 🐯

#124 feat: 본인인증 및 회원가입 api 연결
  App.tsx
  package.json
  src/apis/authService.ts
  src/apis/axiosInstance.ts
  src/screens/sign/SignUpScreen.tsx
  src/types/index.ts
  src/types/user/UserTypes.ts
  src/types/user/index.ts
Labels: Feat 🐯

#117 feat: 취향 이상형 월드컵
  package.json
  src/apis/axiosInstance.ts
  src/assets/index.ts
  src/components/CardImage/CardImage.tsx
  src/navigators/StackNavigator.tsx
  src/screens/generateCard/GenerateCardScreen.tsx
  src/screens/worldcup/card/winner/CardWorldCupWinnerScreen.styled.ts
  src/screens/worldcup/card/winner/CardWorldCupWinnerScreen.tsx
  src/screens/worldcup/select/WorldCupSelectScreen.tsx
  src/screens/worldcup/taste/TasteWorldCupScreen.tsx
  src/screens/worldcup/taste/selectCategory/SelectCategoryScreen.tsx
  src/screens/worldcup/taste/winner/TasteWorldCupWinnerScreen.styled.ts
  src/screens/worldcup/taste/winner/TasteWorldCupWinnerScreen.tsx
  src/types/card/CardTypes.ts
Labels: Feat 🐯

#125 feat: 챌린지 방 가입하기
  src/screens/product/complete/ProductSignInScreen.tsx
Labels: Feat 🐯

#130 feat: 나만의 카드 생성 -> 이상형 월드컵 우승 화면 전환
  src/apis/axiosInstance.ts
  src/screens/generateCard/GenerateCardScreen.tsx
  src/screens/hana/HanaMainScreen.tsx
  src/screens/worldcup/card/winner/CardWorldCupWinnerScreen.tsx
Labels: enhancement

#133 feat: 기상 인증 api 통신
  src/apis/wakeupService.ts
  src/screens/wakeup/camera/CameraScreen.styled.ts
  src/screens/wakeup/camera/CameraScreen.tsx
  src/screens/wakeup/wakeup/WakeupScreen.tsx
Labels: Feat 🐯

#140 feat: 전체 상품 조회 api 통신
  .vscode/launch.json
  src/apis/axiosInstance.ts
  src/apis/productService.ts
  src/constants/Product.ts
  src/constants/WakeupObject.ts
  src/screens/product/allproduct/ProductScreen.styled.ts
  src/screens/product/allproduct/ProductScreen.tsx
  src/screens/worldcup/card/winner/CardWorldCupWinnerScreen.tsx
  src/types/product/ProductTypes.ts
Labels: enhancement, Feat 🐯

#138 feat: 퀴즈 api 연결
  src/apis/axiosInstance.ts
  src/assets/splash.png
  src/screens/generateCard/GenerateCardScreen.tsx
  src/screens/quiz/QuizScreen.tsx
  src/screens/worldcup/card/winner/CardWorldCupWinnerScreen.styled.ts
  src/types/common/CommonTypes.ts
  src/types/quiz/QuizTypes.ts
Labels: Feat 🐯

#151 feat: 마이페이지 API 연결
  src/apis/axiosInstance.ts
  src/screens/mypage/MyPageScreen.tsx
  src/screens/mypage/challengingTabView/ChallengingTabView.tsx
  src/screens/mypage/challengingTabView/tabContens/myChallenging/MyChallenging.tsx
  src/screens/mypage/challengingTabView/tabContens/waitingChallenging/WaitingChallenging.tsx
  src/screens/mypage/myAccountView/MyAccountView.tsx
  src/types/group/GroupTypes.ts
  src/types/mypage/MyPageTypes.ts
Labels: enhancement

#150 feat: Splash 화면 추가
  package.json
  src/screens/hana/HanaMainScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
  src/screens/home/HomeScreen.tsx
Labels: enhancement

#149 feat: 경쟁화면 개발 및 오늘의 챌린지 화면으로 이동
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/screens/ExampleScreen.tsx
  src/screens/compation/CompetitiveScreen.styled.ts
  src/screens/compation/CompetitiveScreen.tsx
  src/screens/pedometer/PedometerScreen.tsx
  src/screens/wakeup/wakeup/WakeupScreen.tsx
  src/types/competition/CompetitionTypes.ts
Labels: Feat 🐯, Style 🌈

#155 feat: 경쟁화면 및 스플래시 컴포넌트
  src/apis/axiosInstance.ts
  src/assets/svg/fifth.svg
  src/assets/svg/first.svg
  src/assets/svg/fourth.svg
  src/assets/svg/index.ts
  src/assets/svg/second.svg
  src/assets/svg/third.svg
  src/components/Splash/Splash.styled.ts
  src/components/Splash/Splash.tsx
  src/screens/compation/CompetitiveScreen.styled.ts
  src/screens/compation/CompetitiveScreen.tsx
  src/screens/sign/SignInScreen.tsx
Labels: Feat 🐯, Style 🌈

#156 feat: 전체 상품 페이지 로딩시 스플래쉬 적용
  src/screens/product/allproduct/ProductScreen.tsx
Labels: Style 🌈

#162 feat 연동 SendSucess insert
  src/screens/bankingService/SendCompleteScreen.tsx
Labels: Feat 🐯

#164 Feat/axios/minjoo/#82
  src/screens/bankingService/SendCompleteScreen.tsx
Labels: Feat 🐯

#163 feat: 입출금 통장 상품 가입 api 통신
  src/apis/productService.ts
  src/screens/product/ProductSignUpScreen.styled.ts
  src/screens/product/ProductSignUpScreen.tsx
  src/screens/product/allproduct/ProductScreen.styled.ts
  src/screens/product/allproduct/ProductScreen.tsx
  src/screens/product/auth/ProductPasswordScreen.tsx
  src/types/account/AccountTypes.ts
Labels: Feat 🐯, Style 🌈

#167 feat: 퀴즈 점수 화면
  src/apis/axiosInstance.ts
  src/assets/quiz/happyQuiz.gif
  src/assets/quiz/o.png
  src/assets/quiz/sadQuiz.gif
  src/assets/quiz/x.png
  src/screens/quiz/QuizScreen.styled.ts
  src/screens/quiz/QuizScreen.tsx
Labels: enhancement

#169 feat:회원가입 페이지로 이동 버튼 css 수정
  src/screens/hana/HanaMainScreen.tsx
  src/screens/sign/InputForm.styled.ts
  src/screens/sign/SignInScreen.tsx
Labels: Style 🌈

#171 feat: 하나은행 메인 화면 css 수정, 상품 조회 탭 버튼 추가
  src/screens/bang/bangDetail/BangDetailScreen.styled.ts
  src/screens/hana/HanaMainScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
Labels: Feat 🐯, Style 🌈

#178 docs: 커스텀 프로필 이미지 추가
  src/assets/2.png
  src/assets/3.png
  src/assets/4.png
Labels: Style 🌈

#179 refactor 작업용 탭 삭제
  src/apis/axiosInstance.ts
  src/navigators/TabNavigator.tsx
  src/screens/ExampleScreen.tsx
  src/screens/ExploreScreen.tsx
  src/screens/hana/HanaMainScreen.tsx
Labels: Refactor ⚒️

#180 feat: 계좌 내역 조회 API 적용
  src/components/Splash/Splash.styled.ts
  src/components/Splash/Splash.tsx
  src/navigators/StackNavigator.tsx
  src/screens/chatbot/ChatBotScreen.styled.ts
  src/screens/chatbot/ChatBotScreen.tsx
  src/screens/hana/HanaMainScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/home/HomeScreen.tsx
  src/screens/sign/InputForm.styled.ts
  src/screens/transactionHistory/TransactionHistoryScreen.tsx
  src/screens/worldcup/information/WorldCupInfoScreen.styled.ts
  src/screens/worldcup/taste/selectCategory/SelectCategoryScreen.tsx
  src/styles/theme.ts
Labels: enhancement

#182 style: 취향 카테고리 선택 이미지 변경
  src/assets/svg/food.svg
  src/assets/svg/index.ts
  src/assets/svg/trip.svg
  src/screens/hana/HanaMainScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
  src/screens/worldcup/taste/selectCategory/SelectCategoryScreen.tsx
Labels: Refactor ⚒️

#186 fix: 버그픽스
  src/apis/axiosInstance.ts
  src/screens/chatbot/ChatBotScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
Labels: bug

#189 fix: 프론트 api 중복 호출 버그 픽스
  src/screens/product/auth/ProductPasswordScreen.tsx
Labels: bug

#193 fix: 마이페이지 진행중인 챌린지 시작, 끝 날짜 인자 타입
  src/apis/axiosInstance.ts
  src/screens/mypage/challengingTabView/tabContens/myChallenging/MyChallenging.tsx
  src/types/group/GroupTypes.ts
Labels: bug

#195 style: 하나은행 메인페이지, 거래내역 조회 css 수정
  src/screens/hana/HanaMainScreen.styled.ts
  src/screens/hana/HanaMainScreen.tsx
  src/screens/product/ProductSignUpScreen.tsx
  src/screens/transactionHistory/TransactionHistoryScreen.tsx
Labels: Style 🌈

#196 fix: 홈 화면으로 이동하기 css 변경
  src/screens/product/complete/ProductSignInScreen.styled.ts
Labels: Style 🌈

#198 fix: 걷기 챌린지 변경
  src/apis/axiosInstance.ts
  src/screens/pedometer/PedometerScreen.tsx
Labels: bug

#200 style: 계좌 이체 화면 css
  src/apis/axiosInstance.ts
  src/screens/bankingService/SendCompleteScreen.tsx
  src/screens/bankingService/SendMoneyScreen.styled.ts
  src/screens/bankingService/SendMoneyScreen.tsx
  src/screens/hana/HanaMainScreen.tsx
  src/screens/transactionHistory/TransactionHistoryScreen.tsx
Labels: Style 🌈
