Repository Do-Farming/do-farming_Front, pull requests merged in 2024-06, with the labels that each got.

#11 feat: 방 찾기 화면
  App.tsx
  package-lock.json
  package.json
  src/components/Title.tsx
  src/screens/ExampleScreen.tsx
  src/screens/ExploreScreen.tsx
  src/screens/bang/BangSearchScreen.styled.ts
  src/screens/bang/BangSearchScreen.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/home/HomeScreen.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
  tsconfig.json
Labels: Feat 🐯

#19 feat: 챌린지 방 상세보기
  App.tsx
  babel.config.js
  package-lock.json
  package.json
  src/assets/1.png
  src/screens/bang/BangSearchScreen.styled.ts
  src/screens/bang/BangSearchScreen.tsx
  src/screens/bang/bangDetail/BangDetailScreen.styled.ts
  src/screens/bang/bangDetail/BangDetailScreen.tsx
  src/screens/bang/bangSearch/BangSearchScreen.styled.ts
  src/screens/bang/bangSearch/BangSearchScreen.tsx
  src/types/BangTypes.ts
Labels: Feat 🐯

#12 feat: 만보기 기능 개발
  App.tsx
  declarations.d.ts
  metro.config.js
  package-lock.json
  package.json
  src/assets/card.png
  src/assets/dofarmingProduct/clock.png
  src/assets/dofarmingProduct/quiz.png
  src/assets/dofarmingProduct/running.png
  src/assets/index.ts
  src/assets/profile.png
  src/assets/svg/ic_run.svg
  src/assets/svg/index.ts
  src/screens/ExploreScreen.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/home/HomeScreen.tsx
  src/screens/pedometer/PedometerScreen.styled.ts
  src/screens/pedometer/PedometerScreen.tsx
Labels: Feat 🐯

#22 fix: 챌린지 방으로 navigate 안되는 이슈 해결
  App.tsx
  src/screens/ExampleScreen.tsx
  src/screens/bang/bangSearch/BangSearchScreen.styled.ts
  src/screens/bang/bangSearch/BangSearchScreen.tsx
Labels: bug

#24 feat: 챌린지 방 만들기 화면 (2/2)
  package-lock.json
  package.json
  src/constants/SelectBox.ts
  src/screens/bang/bangCreate/BangCreateScreen.styled.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/types/BangTypes.ts
Labels: Feat 🐯

#28 feat: 로그인, 회원가입 화면
  App.tsx
  src/components/LongButton.styled.ts
  src/components/LongButton.tsx
  src/screens/ExampleScreen.tsx
  src/screens/login/InputForm.styled.ts
  src/screens/login/LoginScreen.tsx
  src/screens/login/SignupScreen.tsx
  src/screens/login/StartScreen.styled.ts
  src/screens/login/StartScreen.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: Feat 🐯

#30 style: 만보계 페이지 디자인 수정
  src/screens/pedometer/PedometerScreen.styled.ts
  src/screens/pedometer/PedometerScreen.tsx
Labels: Style 🌈

#31 feat: 커스텀 모달
  package-lock.json
  package.json
  src/components/CustomModal/CustomModal.styled.ts
  src/components/CustomModal/CustomModal.tsx
  src/screens/bang/bangCreate/BangCreateScreen.styled.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/screens/bang/bangSearch/BangSearchScreen.tsx
Labels: Feat 🐯

#32 feat: 두파밍 상품 가입 출금 계좌 설정
  App.tsx
  src/components/CustomModal/CustomModal.styled.ts
  src/mocks/userAccount.ts
  src/screens/bang/bangCreate/BangCreateScreen.tsx
  src/screens/bang/bangJoin/BangJoinScreen.styled.ts
  src/screens/bang/bangJoin/BangJoinScreen.tsx
  src/styles/theme.ts
Labels: Feat 🐯

#35 feat: 경쟁화면 제작
  App.tsx
  package.json
  src/assets/svg/ic_doFarming.svg
  src/assets/svg/index.ts
  src/screens/ExploreScreen.tsx
  src/screens/compation/CompetitiveScreen.styled.ts
  src/screens/compation/CompetitiveScreen.tsx
  src/types/competition/CompetitionTypes.ts
  src/types/competition/index.ts
  src/types/index.ts
Labels: Feat 🐯

#38 feat: 상품 가입페이지 제작
  App.tsx
  package-lock.json
  package.json
  src/assets/svg/ic_greenCheck.svg
  src/assets/svg/index.ts
  src/screens/ExploreScreen.tsx
  src/screens/home/HomeScreen.styled.ts
  src/screens/product/ProductSignUpScreen.styled.ts
  src/screens/product/ProductSignUpScreen.tsx
  src/screens/product/auth/ProductPasswordScreen.styled.ts
  src/screens/product/auth/ProductPasswordScreen.tsx
  src/screens/product/complete/ProductSignInScreen.styled.ts
  src/screens/product/complete/ProductSignInScreen.tsx
Labels: Feat 🐯

#41 fix: 라우팅 오류 수정
  App.tsx
Labels: bug
